// <auto-generated />
using InfoSellers.Model.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfoSellers.Model.Migrations
{
    [DbContext(typeof(InfoSellersContext))]
    [Migration("20191204202447_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InfoSellers.Model.Entities.BikeSeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("FullName");

                    b.Property<string>("NIT");

                    b.Property<double>("PenaltyPercentage");

                    b.Property<int>("Phone");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("BikeSeller");
                });

            modelBuilder.Entity("InfoSellers.Model.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ComissionValue");

                    b.Property<string>("CommissionType")
                        .IsRequired();

                    b.Property<string>("RoleName");

                    b.Property<int>("RoleOfBikeSellerId");

                    b.HasKey("Id");

                    b.HasIndex("RoleOfBikeSellerId")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("InfoSellers.Model.Entities.Role", b =>
                {
                    b.HasOne("InfoSellers.Model.Entities.BikeSeller", "BikeSeller")
                        .WithOne("Role")
                        .HasForeignKey("InfoSellers.Model.Entities.Role", "RoleOfBikeSellerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
